name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd server; docker build . --tag "wallpaper_wizard:${{ github.sha }}"
    - name: Login to registry 
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u clemenz5 --password-stdin
    - name: Tag image
      run: docker tag "wallpaper_wizard:${{ github.sha }}" ghcr.io/clemenz5/wallpaper_wizard:${{ github.sha }}
    - name: Push image
      run: docker push ghcr.io/clemenz5/wallpaper_wizard:${{ github.sha }}
    