name: Docker Image CI

on:
  push:
    branches: [ "staging", "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd server; docker build . --tag "wallpaper_wizard:${{ github.sha }}"
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "wallpaper_wizard:${{ github.sha }}"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    steps:
    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "wallpaper_wizard:${{ github.sha }}"
    - name: Login to registry 
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u clemenz5 --password-stdin
    - name: Tag image
      run: docker tag "wallpaper_wizard:${{ github.sha }}" ghcr.io/clemenz5/wallpaper_wizard:${{ github.sha }}
    - name: Push image
      run: docker push ghcr.io/clemenz5/wallpaper_wizard:${{ github.sha }}
    